name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"

      - name: Display the version of go that we have installed
        run: go version

      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0

      - name: Build binaries
        run: |
          mkdir ./release
          just all

      - name: List the actions-run-times executables
        run: ls -lh ./release/

      - name: Upload the binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/actions-run-times-*
          file_glob: true
